alexcrichton/curl-rust

curl-sys/Cargo.toml

As https://github.com/rust-lang/rust/pull/19790 is hopefully landing soon, but https://github.com/rust-lang/cargo/issues/1007 is still open, it would be good to add this dependency. (Now, cargo builds need manual touchups after pulls.)

Make `curl-sys` depend on `openssl-sys` for `aarch64-unknown-linux-gnu` triple as well

---

Cargo.toml
curl-sys/Cargo.toml

this is needed to bootstrap cargo on Bitrig.

adding support for bitrig

---

Cargo.toml
curl-sys/Cargo.toml
curl-sys/build.rs

Previously the openssl dependencies were not declared for Android targets.
Also changed the cargo build scripts a bit to mention that we are trying to
compile libcurl from source. This can be helpful if the compilation fails
and the user wants to know why.
(Compiling libcurl from source didn't fail for me - I just wanted to use my prebuilt cross-compiled libcurl by setting PKG_CONFIG_PATH but I didn't know PKG_CONFIG_ALLOW_CROSS before..)

Android support in Cargo.toml.

---

Cargo.toml
curl-sys/Cargo.toml

Add `powerpc-unknown-linux-gnu` to the list of supported triples. This is blocking a native cargo build for powerpc. That being said, I'm not sure if I need to do anything other than add this dependency.

PowerPC Support

---

test/server.rs
test/test_head.rs

Failed build: https://travis-ci.org/carllerche/curl-rust/builds/118506514
The main issue:
```
test/test_head.rs:23:13: 23:33 error: unable to infer enough type information about `_`; type annotations or generic parameter binding required [E0282]
test/test_head.rs:23     assert!(res.get_body() == []);
^~~~~~~~~~~~~~~~~~~~
test/test_head.rs:23:5: 23:35 note: in this expansion of assert! (defined in <std macros>)
test/test_head.rs:23:13: 23:33 help: run `rustc --explain E0282` to see a detailed explanation
```

Fix compilation error, resolve warnings

---

Cargo.toml

Since `Url` is (indirectly) part of the public API, I think this is a breaking change.
It would be possible to depend on `url = ">= 0.5, < 2.0"` (so that this wouldn’t be a breaking change) if `as_str` is reverted to `to_string`, but that would leave an unnecessary `String` allocation.
`test_proxy` fails for me locally with "Timeout was reached", but it also does on master.

Upgrade to rust-url 1.0

---

Cargo.toml
README.md
curl-sys/lib.rs
src/easy.rs
src/error.rs
src/lib.rs
src/multi.rs
tests/multi.rs
tests/server/mod.rs

Bind the libcurl multi interface

---

curl-sys/build.rs

This fixes `curl-sys` compilation on Solaris, which requires explicit link with `libnls` for `inet_ntop` and `inet_pton` symbols.

Fix compilation on Solaris/Illumos

---

src/easy.rs

The method is implemented using CURLOPT_PROGRESS* callbacks, not CURLOPT_XFERINFO*

Fix incorrect CURLOPT doc for `progress_function`

---

curl-sys/build.rs

the old form caused `configure` to probe the environment using some
tests that looked like this:
```
$ $TARGET-gcc conftest.c
$ ./conftest
```
which always failed because `conftest` could have been compiled for e.g.
MIPS but was being called from a x86_64 system.
With the new form, `configure` never call `conftest` in its tests.
r? @alexcrichton

curl-sys: fix call to `configure` in build script

---

curl-sys/lib.rs
src/multi.rs
tests/multi.rs

[curl_multi_wait](https://curl.haxx.se/libcurl/c/curl_multi_wait.html) is the recommended function for performing requests with the multi API.
I'm not sure about the `i32` timeout parameter. While it matches the curl API, a `Duration` would probably be nicer. These have a larger range though, so we'd either have to return an error or clamp to the largest `i32` for huge timeout values.
`curl_multi_wait` was introduced five years ago in curl 7.28.0 which is probably the minimum required curl version then.

Add Multi::wait function

---

curl-sys/build.rs

Copy zlib.lib instead of linking it to zlib_a.lib since exFAT does not support hard- or soft-linking files.
Closes #152.

Windows: Copy zlib.lib instead of hard-linking it

---

curl-sys/build.rs

If the PSL (Public Suffix List) library is installed on the host, curl's `configure` script will enable it, but the curl-sys `build.rs` doesn't include it in the library list, so subsequent linking with libcurl-sys will fail. Since curl-sys doesn't need PSL support, it's best to disable it explicitly.

Explicitly disable PSL support for curl-sys

---

appveyor.yml
curl-sys/Cargo.toml
curl-sys/build.rs

@alexcrichton, a while ago I asked you for a suggestion for a library that I should use to test the vcpkg build helper on, and you suggested curl-sys. 
This PR adds support for getting libcurl from a vcpkg tree (for MSVC ABI builds). It requires vcpkg enabled versions of all of the sys crates that it depends on, which I have also made PRs for. (zlib, libssh2, openssl.) The version of libssh2 in the vcpkg ports tree depends on openssl, whereas the present version uses WinCNG, so the new search requires feature `use-vcpkg`to avoid giving everyone a dependency on openssl.
I have no specific use for vcpkgified versions of curl/ssh2/zlib - these were just used as an example to prove out the mechanism. It doesn't really add much since curl and libssh2 already seamlessly build themselves.
The …

optionally use static or dynamic build of libcurl from vcpkg

---

curl-sys/build.rs

When building against a customized vcpkg installation, libcurl may depend on fewer things. Try the things it might depend on but don't fail if they are not present.
@pravic, this should address the panic() you describe in https://github.com/alexcrichton/curl-rust/pull/166#pullrequestreview-43907908

don't panic if typical dependencies are not available in vcpkg

---

Cargo.toml
curl-sys/lib.rs
src/easy/handler.rs
src/lib.rs

Leverage the open socket callback in libcurl to open all sockets with CLOEXEC,
leveraging `socket2` to provide the necessary runtime support.

Open all sockets with CLOEXEC

---

tests/post.rs

I run git with core.autocrlf=true. This test is sensitive to line endings in the uploaded file.
If you'd rather, I think it's possible to fix this with .gitattributes, telling git not to touch the line endings.

make file upload test tolerant of line ending changes in test file

---

curl-sys/build.rs

Like OSX, Haiku always has libcurl available, so share the same
logic here.

Haiku: unconditionally add libcurl.

---

Cargo.toml
appveyor.yml
curl-sys/lib.rs
src/easy/handle.rs
src/easy/handler.rs
src/easy/mod.rs
src/easy/windows.rs
src/lib.rs
systest/build.rs

This is a first cut of pulling certificates from the windows cert store into openssl as discussed in https://github.com/alexcrichton/curl-rust/pull/185. It works, but only for dynamically linked builds since the required APIs are not accessible in a static build.
The appveyor build was previously a `target-feature=+crt-static` static build. I obviously had not run the systests with a DLL build - they fail with lots of these:
```
bad curl_formadd function pointer: rust: 140700645719848 (0x7ff76c01ff28) != c 140719549205408 (0x7ffbd2be4ba0)
```
(from https://ci.appveyor.com/project/mcgoo/curl-rust/build/job/ee7opiuiayrniykq)
Any thoughts on what would cause that and how to chase it down?
cc: @sfackler

if openssl dlls are loaded, populate the openssl cert store from the windows cert store

---

curl-sys/build.rs

Curl uses libidn2, libidn is gone. The `--without-libidn` has no effect.
I found this while building statically-linked binaries of cargo for
DragonFly (which fails without this option).

Replace --without-libidn with --without-libidn2

---

src/multi.rs

Add accessors to the inner handler type that mirror the ones provided by `Easy2`. Useful if a callback handler has internal state useful to read while a request is active.
For context, I am currently writing code that encapsulates curl which handles buffering in a streaming/incremental way. Right now to access the buffer I have to put it in an `Rc<RefCell<T>>` so that both the callback struct and the rest of the code can access it.
I'm not 100% knowledgeable about libcurl's thread and lifetime requirements, but from what I understand accessing the callback data is OK (just not the `Easy2` itself).

Accessors for handler even after attached to multi

---

curl-sys/lib.rs
src/multi.rs
systest/build.rs

The docs are mostly copied from https://curl.haxx.se/libcurl/c/CURLMOPT_PIPELINING.html.

Add support for CURLMOPT_PIPELINING

---

Cargo.toml
tests/multi.rs

error log:
```
test result: ok. 28 passed; 0 failed; 1 ignored; 0 measured; 0 filtered out
Running target/x86_64-apple-darwin/debug/deps/multi-c453e94ed395bda6
running 3 tests
test smoke ... ok
test smoke2 ... ok
thread '<unnamed>' panicked at 'unexpected header: "" (remaining headers {"Accept: */*\r\n", "\r\n", "Content-Length: 131072\r\n", "PUT / HTTP/1.1\r\n", "Host: 127.0.0.1:54854\r\n"})', tests/server/mod.rs:64:21
test upload_lots ... FAILED
failures:
---- upload_lots stdout ----
thread 'upload_lots' panicked at 'assertion failed: interest <= MASK_4', /Users/hattori-h/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.14/src/poll.rs:2538:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
child server thread also failed: Any
failures:
upload_lots
test result: FAILED. 2 passed; …
```

fix test on macOSX environment

---

Cargo.toml
curl-sys/Cargo.toml

The create does not compile with `cargo build -Z minimal-versions` because a lot of minimal versions are underspecified. I bumped them until I could build successfully.
Ideally we should also add something like `cargo update -Z minimal-versions && cargo build` to the Travis CI config so that this does not happen again in the future. I'm not sure where to put that exactly?

fix(cargo): Update minimal dependency versions so that 'cargo build -Z minimal-versions' works

---

curl-sys/Cargo.toml

Follow-up to #205 .
Sorry, I thought that "0.1.2" would allow any later version, but cargo interprets that as 0.1.x only. We want libz-sys 1.x also.

fix(cargo): Install highest possible libz-sys dependency version

---

src/easy/handle.rs
src/easy/handler.rs

Hi, I needed this CURLINFO_CONTENT_LENGTH_DOWNLOAD option in my binary, so I just added it
but I'm very new to rust, like less than a week, so if you can please review this PR I would appreciate
thanks

added support for CURLINFO_CONTENT_LENGTH_DOWNLOAD

---

src/multi.rs

Expose the pause/unpause interface to easy handles even after they are attached to a multi handle. This allows you to suspend/resume individual transfers when using the multi interface (for example, if your callbacks are interacting with non-blocking I/O and receive `WouldBlock`).
Yeah, another thing I need for [cHTTP](https://github.com/sagebind/chttp)...

Add unpause methods for handles attached to multi

---

.gitmodules
curl-sys/build.rs

It looks like it's basically not possible for MSVC to pick up nghttp2 otherwise
because that detection requires `pkg-config`. I'm sort of personally real tired
of dealing with build systems, so instead use the `cc` crate to do everything.
This commit switches builds from source to always use the `cc` crate and we
manually list all the relevant `#define` directives as well as the list of files
that we're interested in. This is likely not reproducing exactly what libcurl
requires 100%, but it's providing a lot of other benefits:
* This build strategy truly will be cross platform modulo us fixing bugs. We can
now actually get dependency detection and such working across all platforms as
we don't rely on external tools.
* We can now use the vanilla upstream `curl` submodule because there's no …

Update to build curl from scratch

---

src/easy/handle.rs

The docs for `Transfer::perform` erroneously said that it was the same as `Easy::transfer`. This should point to `Easy::perform` instead.

Point docs for Transfer::perform to Easy::perform

---

Cargo.toml
curl-sys/Cargo.toml
curl-sys/build.rs
curl-sys/lib.rs
src/easy/handler.rs
src/lib.rs

For work-reasons we want to use curl without `openssl` support (mostly to save binary sizes). This pull requests just makes `openssl` optional under a feature with the same name.

Make the openssl dependency optional (with default on).

---

curl-sys/build.rs

Ever since rust started using static builds (rust-lang/rust#54919), HTTP/2 hasn't been working on MacOS. The static feature is using the darwinssl backend, which looks like it needs a define to enable some conditional logic to enable ALPN to detect if HTTP/2 is available.
I have no idea if this is safe/wise, but in limited testing on my 10.14 system it seems to work. IIUC, rustc builds on 10.13, so I think these should still apply there.  I think `__builtin_available` was introduced in Xcode 9, but I'm not sure.

Support HTTP/2 on static curl-sys on MacOS.

---

curl-sys/Cargo.toml

I'm thoroughly confused, as the commit at https://github.com/alexcrichton/curl-rust/commit/2783a574e5fbcf722387b70ec792ecfc0f79f367 doesn't seem to exist on any branch.  I was trying to `[patch]` it and took me a bit to figure out why my version was out of date.

Bump curl-sys to 0.4.13

---

curl-sys/build.rs
curl-sys/lib.rs

They are only used so that the corresponding native libraries are linked
in to the static cURL library. This is not needed when building against
the system library:
- If it's a shared library, it is linked against them already and they
are not a part of the public interface.
- Both pkgconfig and vcpkg deal with these dependencies and provide
the right link args to cargo.

Do not mention *_sys crates if they are not needed.

---

.travis.yml
build.rs
ci/Dockerfile-centos7
src/easy/handler.rs
src/lib.rs

curl_global_init() alreary initializes OpenSSL correctly.

Remove unnecessary call to openssl_sys::init()

---

README.md

As discussed in the cargo-vendor context.
If you think that the hint is also too prominent here, I can create a separate troubleshooting file.
Thank you very much for creating and maintaining such crucial crates besides all your other work.

README.md: add troubleshooting section with NSS SSL hint

---

src/easy/handler.rs

Now there have no comfortable way to set proxy type for more than one handler since `Easy::proxy_type` takes the ownership of a `ProxyType` enum. Deriving a `Clone` trait for `ProxyType` ensures such code possible:
``` rust
let proxy = read_proxy_type();
let handler1 = Easy::new();
let handler2 = Easy::new();
handler1.proxy_type(proxy.clone());
handler2.proxy_type(proxy.clone());
```
It will be better to modify the `Easy::proxy_type` function itself. But deriving a `Clone` trait is not harmful.

derive Clone for ProxyType

---

curl-sys/build.rs

Looks like this enables a few optimizations internally, such as reusing
connections! Let's be sure to enable this for our platforms, which
should all have this, so we can get those performance optimizations with
HTTP.

Enable HAVE_GETPEERNAME when building `curl`

---

curl-sys/build.rs

Configure libcurl to use more accurate means of time measurement for use with various calculations, such as `CURLINFO_TOTAL_TIME`.

Fix Curl_now() timer resolution

---

curl-sys/build.rs

I tried running a binary built with the `static-curl` feature on macOS El Captian, and got the following error:
```
dyld: Symbol not found: _clock_gettime
Referenced from: /..../my_binary (which was built for Mac OS X 10.13)
Expected in: /usr/lib/libSystem.B.dylib
```
Apparently `clock_gettime` wasn't added until macOS 10.12.
There is a similar [issue](https://github.com/curl/curl/issues/2905) for `curl` which says to not define `HAVE_CLOCK_GETTIME_MONOTONIC`, so I changed this in the `build.rs` and everything seems to be working fine.

Improve support for older macOS versions

---

curl-sys/build.rs

On OSX we need to link against the clang runtime, which is hidden in some non-default path.
We can get the path from `clang --print-search-dirs`.
Kudos to @ehuss for finding that workaround.
Fixes #279.

Link against clang runtime on static builds on macOS

---

.github/workflows/main.yml

I've found that sometimes the package server IP addresses are out of date on the Actions Ubuntu environments until you `apt update`. I noticed that `master` had failed on this.

Fix install of libkrb5-dev in CI

---

curl-sys/Cargo.toml

I'd like to pull in https://github.com/alexcrichton/curl-rust/pull/283 downstream so that I can handle https://github.com/sagebind/isahc/issues/68. Master has everything needed now, I just need a new version published...

Version bump curl-sys

---

curl-sys/lib.rs
src/easy/handler.rs
systest/build.rs

HTTP/3 support in libcurl is still experimental at this point, but the constant for requesting it is stable. This just defines the constant and makes it available in the `curl` crate.

Define HTTP/3 constant

---

.github/workflows/main.yml

Waiting for upstream fixes, so let's unbreak our own CI to avoid
blocking on that.
Closes #337

Pin nightly to fix CI

---

src/lib.rs

As mentioned in #333, this is a potentially helpful addition that ensures that curl is initialized on the main thread by using constructor functions that get called by the OS before the current program's `main` is called.
This has the advantage that, assuming you are on one of the supported platforms, `init()` will be called safely, correctly, and automatically without concerning the user about the gotchas.
This does have some disadvantages:
- Constructor functions are always invoked, which means that simply including curl can slow down the startup of a user's program even if curl is only conditionally used, or used later in program execution.
- On platforms without a constructor implementation, the user still needs to initialize curl on the main thread. All the common platforms are …

Experimental use of constructor functions to call init

---

src/easy/handle.rs
src/easy/handler.rs

The existing `unix_socket` method has some limitations in its design:
- You cannot unset a previously set path.
- You cannot set non-UTF-8 paths.
This adds a second method named `unix_socket_path` that instead takes an `Option<impl AsRef<Path>>` which more closely aligns with what libcurl accepts for this option. We could consider soft-deprecating `unix_socket`, but I left it alone for now.

Add unix_socket_path that exposes more Unix socket control

---

curl-sys/build.rs

Define `HAVE_GETSOCKNAME` for bundled curl-sys so that `Easy2::local_ip` and `Easy2::local_port` don't return blank values. We're already enabling `HAVE_GETPEERNAME` and your system probably has `getsockname` if it has `getpeername`.

Enable HAVE_GETSOCKNAME for bundled build

---

Cargo.toml
curl-sys/Cargo.toml

Upgrade to libz-sys 1.1.0. Add a feature zlib-ng-compat to build with
zlib-ng in zlib-compat mode. This requires building our own curl (as
system curl will link with another zlib), so make zlib-ng-compat require
static-curl.

Add support for zlib-ng

---

src/easy/handler.rs

Probe for OpenSSL certificates only once

---

Cargo.toml

Upgrades to a version not making invalid assumptions about the memory layout of `std::net::SocketAddr`.
Helps unblock https://github.com/rust-lang/rust/pull/78802. See that PR for more details.

Upgrade socket2 dependency

---

curl-sys/lib.rs
src/version.rs

Added some fields which were tacked on recently plus went ahead and
added indicators of the two Rust crate versions as well.

Add some more fields to `Debug for Version`

---

curl-sys/build.rs

This change allows us to set the location for GSSAPI.
This would be useful on systems where the library is not found at the usual location [`/usr`](https://github.com/curl/curl/blob/master/configure.ac#L1417) or if the client wants to set it manually.
I tried to make the behaviour similar to [`DEP_NGHTTP2_ROOT`](https://github.com/theawless/curl-rust/blob/master/curl-sys/build.rs#L218).

Add environment variable to find GSSAPI

---

src/multi.rs

Fix a copy and paste error that showed the value of the `input` flag of `Events` in place of the `output` and `error` flags in the debug formatting.

Fix debug formatting for Events struct

---

curl-sys/build.rs

The `TCP_NODELAY` macro/constant was not being defined during compilation for the bundled libcurl build on Unix systems because `netinet/tcp.h` was not being included. It is difficult to verify that this is working properly without a debugger or strace. I've confirmed this fix on Linux and macOS.
Also rearrange some of the defines to help keep the build script somewhat organized.
Fixes #379.

Fix TCP_NODELAY not defined for static builds on Unix

---

Cargo.toml
curl-sys/lib.rs
examples/ssl_cert_blob.rs
src/easy/handle.rs
src/easy/handler.rs
systest/build.rs

This adds support for [passing SSL certificates as in-memory blobs](https://github.com/curl/curl/pull/5357/commits/c92a862cb7ab4c16757def851190adfced6ac485) using several new options added in libcurl `7.71.0`:
- [`CURLOPT_SSLCERT_BLOB`](https://curl.se/libcurl/c/CURLOPT_SSLCERT_BLOB.html)
- [`CURLOPT_SSLKEY_BLOB`](https://curl.se/libcurl/c/CURLOPT_SSLKEY_BLOB.html)
- [`CURLOPT_PROXY_SSLCERT_BLOB`](https://curl.se/libcurl/c/CURLOPT_PROXY_SSLCERT_BLOB.html)
- [`CURLOPT_PROXY_SSLKEY_BLOB`](https://curl.se/libcurl/c/CURLOPT_PROXY_SSLKEY_BLOB.html)
- [`CURLOPT_ISSUERCERT_BLOB`](https://curl.se/libcurl/c/CURLOPT_ISSUERCERT_BLOB.html)
Notably, this PR does not add support for `CURLOPT_PROXY_ISSUERCERT_BLOB` since this crate does not presently support `CURLOPT_PROXY_ISSUERCERT` (and adding …

Add support for in-memory certificates

---

Cargo.toml
curl-sys/Cargo.toml
curl-sys/build.rs
curl-sys/lib.rs
examples/ssl_cert_blob.rs
examples/ssl_proxy.rs
src/easy/form.rs
src/easy/handle.rs
src/easy/handler.rs
src/easy/list.rs
src/easy/windows.rs
src/lib.rs
src/multi.rs
src/version.rs
systest/Cargo.toml
systest/build.rs
systest/src/main.rs
tests/atexit.rs
tests/easy.rs
tests/multi.rs
tests/post.rs
tests/protocols.rs

Just update to edition 2018 before edition 2021 coming.

Upgrade project to edition 2018

---

curl-sys/build.rs

I've noticed recently that when using the bundled curl version on macOS, very occasionally curl will get "stuck" in the TCP connection phase when using the multi interface. Apparently this is caused by the `poll()` implementation not behaving quite as the POSIX standard says it should on some macOS versions. (Curl uses `poll()`/`select()` to check if a socket has finished connecting without blocking, even if you are not using those functions to poll read/write readiness.)
This originally was a problem just for macOS 10.12, but after a recent update it seems like this regression might have come back in 10.15. It is more reliable to just disable `poll()` completely on macOS, which the official build configuration does here: https://github.com/curl/curl/blob/1e19eceb50d6d8b9c9b37e2f8e1259b2f3 …

Disable compiling with poll() on macOS

---

systest/Cargo.toml
systest/build.rs

This swaps out ctest with a fork which has been updated to be able to compile on newer rustc versions. This fixes the failing tests on nightly in CI recently introduced.
Long-term we should consider moving off of ctest, but that's a larger effort with more unknowns.

Update ctest to ctest2

---

Cargo.toml
curl-sys/build.rs
curl-sys/lib.rs
examples/aws_sigv4.rs
src/easy/handle.rs
src/easy/handler.rs
systest/build.rs

Used these platforms:
* Windows10 + MSVC 14.29
* macOS Big Sur + Apple clang 12.0
* Linux 5.4 + GCC 7.3
I wasn't sure what feature combinations to build curl-rust with to test properly.
So, I wrote [this script](https://github.com/theawless/curl-rust/commit/4d4fca5c54772d47e6376045adf56dc2226fc38c) which runs all of them (1024 combinations).
Would it be useful to add it in the CI somehow?
For macOS and Linux, all builds work fine.
For Windows, some of them are breaking, but they had been breaking before my changes. 
`mesalink` + `spnego` doesn't build together on Windows. Is this expected?
Closes https://github.com/alexcrichton/curl-rust/issues/392

Add support for aws-sigv4 authentication

---

curl-sys/build.rs

When doing local development on Linux, if any of the curl source files are changed, cargo will not trigger a rebuild. This is because pkg_config prints various rerun-if-env-changed values which prevents scanning for source file changes. This adds a basic rerun-if-changed to pick up any changes to the curl submodule.
The only downside to this is if the package is being built before initializing the submodule, [this code](https://github.com/alexcrichton/curl-rust/blob/8eb27f7c3427c6f730313f49aeeddf814c5b2bb1/curl-sys/build.rs#L43-L47) will initialize it, but with a timestamp after the build started.  This means the second cargo command will rebuild *again*, unfortunately.  I don't think there is any way to avoid this, and I think should be sufficiently rare not to matter.  CI here …

Trigger rebuild if a curl source file has changed.

---

curl-sys/build.rs
curl-sys/lib.rs
src/version.rs

This adds whether or not libgit2 was built with the vendored version or not.
My use case is to expose this information in Cargo (per https://github.com/rust-lang/cargo/issues/6275).

Add vendored field to Version information.

---

src/lib.rs

This commit should fix an issue that showed up in rust-lang/cargo#10013
where curl's initialization was accidentally detecting that curl needed
an early initialization (due to sfackler/rust-openssl#1548). This early
initialization caused the later env-vars set by `openssl-probe` to not
actually be read since OpenSSL was already initialized. While not an
issue for `curl` I think it does pose an issue for other libraries like
libgit2 using OpenSSL.
The fix here is to initialize the env vars before OpenSSL, which should
have OpenSSL pick up the probe results.

Initialize openssl-probe env vars if curl requires init

---

src/multi.rs

Add a drop handler that guarantees that `curl_multi_remove_handle` is always called on easy handles added to a multi handle before the easy handle is dropped. Based on https://github.com/curl/curl/issues/7982, we should not be allowing users to drop a previously attached handle without first calling `curl_multi_remove_handle`. In curl versions between 7.77 and 7.80 this could cause a crash under certain circumstances. While this will likely be fixed in the next curl version, it is still recommended to not allow this, plus we must still handle this case for users who may not have updated to a patched libcurl.
I'm not totally happy with how this is implemented as it adds an `Arc::clone` call every time an easy handle is added to a multi handle, but I couldn't think of a better way of …

Guarantee that curl_multi_remove_handle is called

---

src/lib.rs

Compilation currently fails for curl on macOS Monterey due to upstream rustc issue https://github.com/rust-lang/rust/issues/90342. To make this problem hurt users less, we can work around this by avoiding the specific issue that this bug causes.
To avoid the rustc issue, we cannot directly reference any symbol that is configured to be in a constructor linker section, which we were previously doing intentionally to work around a different rustc issue https://github.com/rust-lang/rust/issues/47384. We should be able to avoid both bugs by defining our constructor symbol as a public item in the root module, though not directly referencing it in other code. Since the root module is always used (`init` is called on-demand in key places in the code) it should not be removed by optimization.
Also …

Refactor init to avoid link bugs on macOS Monterey

---

curl-sys/Cargo.toml

I didn't see any urgent fixes in the release notes so this doesn't bump the `*-sys` crate version yet.

Update to curl 7.81.0

---

Cargo.toml
README.md
ci/run.sh
curl-sys/Cargo.toml
curl-sys/build.rs
curl-sys/lib.rs
examples/https.rs

This adds experimental support for using rustls as a TLS backend for curl. This is made possible by the upstream rustls support recently added to curl via [rustls-ffi](https://github.com/rustls/rustls-ffi).
See #341.

Add experimental support for rustls

---

src/easy/handle.rs
src/easy/handler.rs
tests/easy.rs

Took a try at addressing #410
Additionally, added tests for download_size.

Add upload_size

---

curl-sys/Cargo.toml
curl-sys/build.rs

Release notes: https://curl.se/mail/lib-2022-04/0053.html
Note that this release fixes multiple just-announced CVEs:
- https://curl.se/docs/CVE-2022-22576.html
- https://curl.se/docs/CVE-2022-27774.html
- https://curl.se/docs/CVE-2022-27775.html
- https://curl.se/docs/CVE-2022-27776.html

Update curl to 7.83.0

---

curl-sys/Cargo.toml

This version contains patches for six new CVEs just published:
- [CVE-2022-27778: curl removes wrong file on error](https://curl.se/docs/CVE-2022-27778.html)
- [CVE-2022-27779: cookie for trailing dot TLD](https://curl.se/docs/CVE-2022-27779.html)
- [CVE-2022-27780: percent-encoded path separator in URL host](https://curl.se/docs/CVE-2022-27780.html)
- [CVE-2022-27781: CERTINFO never-ending busy-loop](https://curl.se/docs/CVE-2022-27781.html)
- [CVE-2022-27782: TLS and SSH connection too eager reuse](https://curl.se/docs/CVE-2022-27782.html)
- [CVE-2022-30115: HSTS bypass via trailing dot](https://curl.se/docs/CVE-2022-30115.html)

Update bundled curl to 7.83.1

---

curl-sys/build.rs

On older systems, it may be necessary to use custom compiler.
So respect whichever compiler user is using to build crate.

Don't assume compiler is system clang on macOS

---

curl-sys/Cargo.toml
curl-sys/build.rs

This version contains patches for five new CVEs:
- [CVE-2022-32205: Set-Cookie denial of service](https://curl.se/docs/CVE-2022-32205.html)
- [CVE-2022-32206: HTTP compression denial of service](https://curl.se/docs/CVE-2022-32206.html)
- [CVE-2022-32207: Unpreserved file permissions](https://curl.se/docs/CVE-2022-32207.html)
- [CVE-2022-32208: FTP-KRB bad message verification](https://curl.se/docs/CVE-2022-32208.html)
- [CVE-2022-35252: control code in cookie denial of service](https://curl.se/docs/CVE-2022-35252.html)
Fixes #457.

Update bundled curl to 7.85.0

---

curl-sys/lib.rs
src/version.rs
systest/build.rs

Following #464 this PR exposes the flag HTTP_proxy (introduced in curl 7.52.0)

Add support for HTTPS proxy feature (#464)

---

curl-sys/Cargo.toml
curl-sys/build.rs

This updates to curl 7.86.0
This includes the fix that was causing issues with http2/tls 1.3/Windows 11 that caused the last release to be yanked. I have tested on Windows 11 and it seems to be working now.
Changelog: https://curl.se/changes.html#7_86_0
There are 4 CVE fixes in this release:
CVE-2022-42916: HSTS bypass via IDN
CVE-2022-42915: HTTP proxy double-free
CVE-2022-35260: .netrc parser out-of-bounds access
CVE-2022-32221: POST following PUT confusion
This release also adds support for websockets. However, I did not add any explicit support for that, though.

Update to 7.86.0

---

Cargo.toml
curl-sys/Cargo.toml
curl-sys/build.rs

Due to some include files being rearranged in more recent versions of curl, the `sys/time.h` header was no longer being included for `timeval.c`, which was causing the error:
```
cargo:warning=curl/lib/timeval.c:106:11: error: call to undeclared function 'gettimeofday'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
cargo:warning=    (void)gettimeofday(&now, NULL);
cargo:warning=          ^
cargo:warning=1 error generated.
```
This fixes it by setting HAVE_SYS_TIME_H which would normally be set by the configure script.
I don't actually know why gcc treats this as a warning, and clang treats it as an error.
Details:
`curl_setup.h` used to include `curl.h` which always [imports `sys/time.h`](https://github.com/curl/curl/blob/3390ef0af08bae32 …

Fix build error with clang

---

curl-sys/lib.rs
src/easy/handler.rs
systest/build.rs

Add the missing curl options that can be found here : https://curl.se/libcurl/c/CURLOPT_SSL_OPTIONS.html

Add missing SSL Options

---

curl-sys/Cargo.toml
curl-sys/build.rs
curl-sys/lib.rs
systest/build.rs

Update libcurl from 7.86 to 7.88.1
Changelog: https://curl.se/changes.html
I haven't really looked at the quic/http3 support, or added any new bindings.

Update libcurl to 7.88.1

---

curl-sys/build.rs

Previously, there were issues cross-compiling the curl library from source on the Haiku platform. That meant that a workaround was added to `build.rs` to always link to the shared library in that case. When testing for the current build, this workaround is no longer necessary, as cross-compiling the curl-sys crate works as expected.
This removes the workaround for this scenario, as it can now use the standard behavior.

curl-sys: remove Haiku cross-compilation workaround

---

src/easy/handler.rs
tests/easy.rs

i32 has a max of 2147483647, if the timeout duration is too big, it causes an overflow.

Use CURLOPT_TIMEOUT if timeout too big

---

curl-sys/Cargo.toml
curl-sys/build.rs

curl 8.0.1 is vulnerable to CVE-2023-{28319..28322}, see https://curl.se/docs/security.html

Update curl to 8.1.0

---

curl-sys/Cargo.toml
curl-sys/build.rs

Updates libcurl from 8.2.0 to 8.2.1
Changelog: https://curl.se/changes.html#8_2_1
Summary: https://daniel.haxx.se/blog/2023/07/26/curl-8-2-1/
This fixes a few regressions in the last release.

Update to curl 8.2.1

---

src/easy/handler.rs

Rust 1.71 added a dropping_references lint which detects a `drop()` of a reference. This was firing in some default trait functions which were using that to avoid the unused variables lint. The workaround here is to just bind them to a wildcard pattern. An alternate solution would be to add `#[allow(unused_variables)]`. Another alternate solution would to use `_` prefixes, but I assume that isn't desirable since that affects the documentation.

Silence dropping_references lint.

---

curl-sys/lib.rs
src/easy/handler.rs

CURL_HTTP_VERSION_3, introduced in curl 7.66.0, has changed with curl 7.88.0. Prior 7.88.0, CURL_HTTP_VERSION_3 implies no fallback if error; since 7.88.0, CURL_HTTP_VERSION_3 can fallback to HTTP/1 or HTTP/2. There is a new flag CURL_HTTP_VERSION_3_ONLY that doesn't fallback. See https://github.com/curl/curl/pull/10264.
Fixes #519.

Fix semantic of `HttpVersion::V3` for  libcurl >= 7.88.0

---

curl-sys/Cargo.toml
curl-sys/build.rs
tests/multi.rs
tests/post.rs

cURL 8.4.0 fixes two vulnerabilities:
- [CVE-2023-38545](https://curl.se/docs/CVE-2023-38545.html), high severity
- [CVE-2023-38546](https://curl.se/docs/CVE-2023-38546.html)

Update to curl 8.4.0

---

Cargo.toml

This sets the minimum version of `curl-sys` to the latest to ensure that the correct version of `curl-sys` is used.
Closes #548

Set minimum version of the curl-sys crate.

---

Cargo.toml

This is needed by the following functions we use in the easy API
Windows suppport:
+ `windows_sys::Win32::System::LibraryLoader::GetProcAddress`
+ `windows_sys::Win32::System::LibraryLoader::GetModuleHandleW`

Add Win32_Foundation feature to windows-sys dep.

---

.github/workflows/main.yml

Releases of garando_syntax 0.1.1 and ctest2 0.4.8 fix the issues that
required the pin.

Un-pin nightly in CI.

---

src/easy/form.rs
src/easy/handle.rs
src/easy/handler.rs
src/easy/list.rs
src/multi.rs

The latest nightly has started warning against redundant imports.

Remove redundant imports.

---

curl-sys/Cargo.toml

These directories within the curl submodule are 5 and 11 MB, respectively, and are not necessary for building curl-sys.

Exclude curl/docs and curl/tests from curl-sys crate

---

curl-sys/build.rs

Try to resolve issue https://github.com/alexcrichton/curl-rust/issues/568

Enable support of  scope ID for IPv6 link local addresses

---

build.rs
curl-sys/build.rs

This removes the warnings about unexpected cfg values introduced in Rust 1.80.

Squelch check-cfg warnings

---

ci/run.sh
curl-sys/Cargo.toml
curl-sys/build.rs

Minor update: https://daniel.haxx.se/blog/2024/09/18/curl-8-10-1/
Closes #572

Update to 8.10.1

---

.github/workflows/main.yml
build.rs
ci/Dockerfile-musl
curl-sys/build.rs

Ref: #575
Closes #576
Closes https://github.com/nabijaczleweli/cargo-update/issues/277
Supplants #577

Use cargo: (universally supported) instead of cargo:: (1.80+ only) syntax for rustc-check-cfg

---

.github/workflows/main.yml
ci/Dockerfile-musl
ci/run.sh
systest/Cargo.toml

Also turn off `fail-fast` on CI to see all the failures on PRs

Use openssl-src instead of building OpenSSL manually

---

curl-sys/Cargo.toml
curl-sys/build.rs

Updates to curl 8.12.0
Release notes: https://curl.se/ch/8.12.0.html
Blog: https://daniel.haxx.se/blog/2025/02/05/curl-8-12-0/

Update to 8.12.0

---

curl-sys/Cargo.toml
curl-sys/build.rs

Release notes: https://curl.se/ch/8.12.1.html
Blog: https://daniel.haxx.se/blog/2025/02/13/curl-8-12-1/
I can't tell if any of these fixes look particularly important. However, it's fairly trivial to bump the submodule.

Update curl to 8.12.1

---

Cargo.toml
curl-sys/Cargo.toml

Addresses #599 
Goal of this is making the `arm64ec-pc-windows-msvc` target triple compile.

Bump `windows-sys` dependency to ver 0.59

---

.github/workflows/main.yml
src/easy/handler.rs

This switches the global static openssl probe to use LazyLock instead of Once. `static mut` refs are now an error in Rust 2024, and this is I believe the preferred method of doing something like this.
LazyLock was added in 1.80 (released 2024-07-25), so the minimum version has to be bumped to that.

Use LazyLock for openssl probe

---

src/easy/list.rs
src/version.rs

This fixes the mismatched_lifetime_syntaxes warning which has started to appear on more recent versions of rustc.

Fix mismatched_lifetime_syntaxes warning

---

.github/workflows/main.yml

This changes the macos CI job to use the aarch64-apple-darwin target instead of x86_64-apple-darwin. The Rust project has demoted x86_64 to tier 2
(https://rust-lang.github.io/rfcs/3841-demote-x86_64-apple-darwin.html), and I think we should be testing the aarch64-apple-darwin target instead since it is tier 1.
macos-latest is currently macos-14 which is aarch64. The x86_64 tests have been running under emulation.

CI: Switch to aarch64-apple-darwin
