- src/ffi/version.rs
- src/http/handle.rs
- src/lib.rs
> Going with change in `Iterator`s.

- src/http/handle.rs
> Update to rust master

- src/ffi/easy.rs
- src/ffi/err.rs
- src/ffi/opt.rs
- src/ffi/version.rs
- src/lib.rs
Please be careful as the proxy test is failing and I have no idea if
that is caused by these changes. At least it should be a starting point
to continue on from.
> (Hopefully) fixes changes in FFI

- curl-sys/lib.rs
- src/ffi/err.rs
- src/http/body.rs
- src/http/handle.rs
- src/http/response.rs
- src/test/server.rs
> Update for fmt changes and derefs

- Cargo.toml
> Bump curl-sys required version

- src/easy.rs
I'm currently trying to port the LastPass command line client from C to Rust and it uses this callback to implement certificate pining: https://github.com/lastpass/lastpass-cli/blob/master/http.c#L292
Given that this is a pretty security-critical piece of code I was conservative with this patch but I'm not entirely satisfied with this Rust implementation from a "quality of life" standpoint.
The problem is that the documentation says that the `ssl_ctx` pointer is simply a pointer to the library's SSL_CTX. I'm not really sure what to do with that, can we assume that it's always an OpenSSL context? If so we could provide a safe `openssl::ssl::SslContext` instead.
The docs mention that it can be used with the "wolfSSL/CyaSSL" libraries as well, but then again I've seen other [hardcoded calls …
> Implement a safe interface to CURLOPT_SSL_CTX_FUNCTION and _DATA.

- curl-sys/lib.rs
- src/easy.rs
Signed-off-by: Silvio Fricke <silvio.fricke@gmail.com>
> Add .netrc binding

- src/easy.rs
Adds bindings for the following options.
- CURLINFO_TOTAL_TIME
- CURLINFO_NAMELOOKUP_TIME
- CURLINFO_CONNECT_TIME
- CURLINFO_APPCONNECT_TIME
- CURLINFO_PRETRANSFER_TIME
- CURLINFO_STARTTRANSFER_TIME
- CURLINFO_REDIRECT_TIME
Is there a better way than transmute in getopt_double?
> Add getters for time

- curl-sys/build.rs
No need to spray build files in the source tree!
> Copy src files into OUT_DIR on msvc

- src/easy/form.rs
Due to a curl oddity if the length is 0 it will call strlen on the
string.  Because there are no trailing nullbytes in rust this will
effectively cause a crash for empty form data.  The workaround is
to ensure that a single null byte is passed for empty form data.
This fixes #176
> Pass null as form contents if length is empty

- curl-sys/build.rs
Also removed some unnecessary (as far as I can see) indirection.
Fixes https://github.com/alexcrichton/curl-rust/issues/189.
> Fix MinGW compilation on drives besides C:

- curl-sys/build.rs
- curl-sys/lib.rs
- src/version.rs
- systest/Cargo.toml
- systest/build.rs
- systest/version_detect.c
- tests/post.rs
> Update curl submodule

- curl-sys/build.rs
This should fix the build of curl-sys whenever http2 support is
requested but the system libcurl doesn't look like it supports HTTP/2
(as is true for older OSX)
> Use static-libcurl on OSX without HTTP/2

- curl-sys/lib.rs
- src/easy/handler.rs
> Support more ssl versions

- src/easy/handler.rs
s/automaticsally/automatically
> Fix typo in comment in handler.rs

- src/easy/form.rs
This is similar in spirit to #176. Turns out there is another case that needs handling.
> Do not crash with a segfault if empty buffer is passed

- src/multi.rs
Expose read-only getters that are safe to invoke while an easy handle is attached to a multi handle.
Also allow users to access the underlying curl pointer if the safe interface is not flexible enough for a given use-case.
Fixes #273.
> Getters on easy handles when attached to multi

- Cargo.toml
- curl-sys/Cargo.toml
Publish recent fixes in curl and curl-sys. I did not bump the minimum curl-sys requirement from curl.
> Version bump

- .github/workflows/main.yml
- Cargo.toml
> Re-export spnego feature from curl-sys

- src/multi.rs
> Fix safety hole in Multi::close and hide it from docs

- curl-sys/build.rs
Just a few tweaks to build logic for now
> Bump curl submodule to 7.71.0

- curl-sys/build.rs
- tests/easy.rs
- tests/server/mod.rs
port of #309 updated to latest master
> added support for unix sockets

- curl-sys/build.rs
Due to several issues, the Haiku build of rustc and cargo is cross-compiled
from a Linux host. In this official build, it is prefered to link to the
libcurl build that is being distributed as an official Haiku port. This
change adds the logic to link to the official libcurl build when
cross-compiling. The previous logic was flawed, in the sense that it would
rely on the hosts curl-config to determine whether http2 support was available.
When doing a native build, pkg_config can be used to determine whether
libcurl is available on the platform, thus removing the need for separate logic
when building curl-sys on Haiku itself.
The change was tested manually on Haiku and in a cross-compile from Linux.
> Haiku: rework build.rs logic for curl-sys

- build.rs
As described in sfackler/rust-openssl#1548
> Update OpenSSL initialization check

- src/easy/handler.rs
Hello, I added an auto function for ergonomic reasons when combining CURLAUTH_BASIC, CURLAUTH_DIGEST, CURLAUTH_GSSNEGOTIATE, and CURLAUTH_NTLM. Please review this PR.
> Added HTTP Auto authentication

- curl-sys/Cargo.toml
- curl-sys/build.rs
https://daniel.haxx.se/blog/2023/03/20/curl-8-0-0-is-here/
https://daniel.haxx.se/blog/2023/03/20/curl-8-0-1-because-i-jinxed-it/
https://curl.se/changes.html
🎂 🎉
> Update curl to 8.0.1

- src/easy/handler.rs
- tests/easy.rs
If the time that was converted into millisecond
is more than the capacity of c_long, it will
overflow, thus we need to convert it into seconds
and use CURLOPT_CONNECTTIMEOUT.
> Use CURLOPT_CONNECTTIMEOUT if timeout too big

- src/easy/handler.rs
- tests/easy.rs
There is no mutation involve when calling
getopt functions.
> Remove mut to all getopt functions

- curl-sys/Cargo.toml
- curl-sys/build.rs
Changelog: https://curl.se/changes.html#8_3_0
Some security vulnerabilities were fixed: https://curl.se/docs/CVE-2023-38039.html
> Update to curl 8.3.0

- curl-sys/Cargo.toml
- curl-sys/build.rs
- tests/easy.rs
A routine update.
Changelog: https://curl.se/changes.html#8_8_0
Fixes #559
> Update curl to 8.8.0

- .github/workflows/main.yml
- ci/Dockerfile-alma8
- curl-sys/Cargo.toml
- curl-sys/build.rs
curl 8.9.0 fixes following vulnerabilities:
- https://curl.se/docs/CVE-2024-6874.html
- https://curl.se/docs/CVE-2024-6197.html
> Update to curl 8.9.0

- Cargo.toml
- curl-sys/Cargo.toml
> Bump versions numbers

- Cargo.toml
- curl-sys/Cargo.toml
One day I might set up auto-publishing but alas it is not yet such a day.
> Bump curl/curl-sys versions
